version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: database.conf
    expose:
      - "5435"
    ports:
      - 5435:5435
    container_name: postgres_database
    command: -p 5435
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin.env
    ports:
      - "80:80"
    depends_on:
      - db

  website:
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    container_name: website

volumes:
  postgres_data:
    
